# -*- coding: utf-8 -*-
{
    "name": "Approval Module",
    "version": "1.0",
    "category": "",
    "description": """ """,
    "website": "https://www.mattobell.com",
    "summary": "This module adds double level of approval to sale/ Purchase/ billing module",
    "sequence": 1,
    "depends": ["sale", "stock", "account", "purchase"],
    "data": [
        "security/approval_security.xml",
        "security/ir.model.access.csv",
        "data/account_email_template.xml",
        "data/hr_email_template.xml",
        "data/purchase_email_template.xml",
        "data/sale_email_template.xml",
        "wizard/billing_popup_view.xml",
        "wizard/purchase_popup_view.xml",
        "wizard/sales_popup_view.xml",
        "views/reject_reason_view.xml",
        "views/account_move_view.xml",
        "views/sales_order_view.xml",
        "views/purchase_view.xml",
        "views/hr_leave_views.xml"
    ],
    "demo": [],
    "test": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
